apiVersion: v1
kind: ConfigMap
metadata:
  name: skedler-config
  labels:
    app: skedler
data:
  reporting.yml: |
    ---
    ######################################### SKEDLER REPORTS CONFIGURATION SETTINGS #########################################
    ################################################## ENVIRONMENT SETTINGS ##################################################
    # The environment where skedler is getting deployed. If you don't have an internet connection on your machine, change this as 'true' and enable `skedlerUsername` & `skedlerPassword` as well.
    # isOfflineEnvironment: false
    # Skedler default username and password. Enable this only if you sets `isOfflineEnvironment` as true. You can change username & password for your convenient to create skedler account.
    # skedlerUsername: 'admin@skedler.com'
    # skedlerPassword: 'admin'
    ##################################################### HOST SETTINGS ######################################################
    # The port which skedler runs
    serverPort: 3000
    # The port which skedler need to run redis
    redisPort: 6379
    # The public facing host name or IP address used to access Skdler from a browser
    host: "0.0.0.0"
    # Protocol (http, https)
    protocol: 'http'
    # To enable SSL certificate Verification, change this as 'false'
    # skipSslVerification: true
    # The path, which you can use for the proxy purpose with skedler, Specially for Ngnix etc. For example: '/skedler'
    # proxyBasePath: '/skedler'
    ##################################################### LOG SETTINGS ######################################################
    # The path where you need to keep the skedler log files, For example: '/var/opt/skedler-xg'. Leave empty for the default path
    # logFilesDir: ''
    ################################################### DATABASE SETTINGS ###################################################
    # The path where you need to keep the database, For example: '/var/lib/skedler-xg'. Leave empty for the default path
    # databasePath: ''
    # Database where skedler is going to store the data, default is 'sqlite'. you can change as 'mysql', If you're using 'mysql' enable the below properties
    # datastore: 'sqlite'
    # Enable and configure only if you are choosing datastore as `mysql`
    # databaseHost: 'localhost'
    # databasePort: 3306
    # accountDatabaseName: 'sks_accounts'
    # tenantDatabaseName: 'sks_tenant'
    # databaseUsername: 'admin'
    # databasePassword: 'password'
    # dialect: 'mysql'
    # Maximum number of connection in pool, default: 5
    # maxConn: 5
    # Minimum number of connection in pool, default: 0
    # minConn: 0
    # The maximum time, in milliseconds, that a connection can be idle before being released, default: 10000
    # connIdleTime: 10000
    # The maximum time, in milliseconds, that pool will try to get connection before throwing error, default: 10000
    # connAcquireTime: 10000

    ################################################### LICENSE SETTINGS ####################################################
    # Specially for Docker/VM to persist the license which has been activated previously
    licenseEmail: 'nasurdheen@guidanz.com'
    licenseKey: 'BE4C3B-7337BC-482BB0-378FB0-F1BD3C-CDA4CA'
    ################################################## MIGRATION SETTINGS ###################################################
    # Specify the datastore you want to migrate from Skedler 4.x For example: sqlite, mysql, elasticsearch
    # migrationSourceDatastore: 'sqlite'
    # The path of the datastore you want to migrate from Skedler 4.x
    # migrationSourceDatastorePath: '/var/lib/skedler/skedler.db'
    # Base path of Skedler 4.x
    # oldSkedlerBasePath: '/var/lib/skedler'
    # Enable and configure only if you are using datastore as `mysql` in Skedler 4.x
    # migrationDatabaseHost: 'localhost'
    # migrationDatabasePort: 3306
    # migrationDatabaseName: skedler
    # migrationDatabaseUsername: 'admin'
    # migrationDatabasePassword: 'password'
    # migrationDialect: 'mysql'
    # Enable and configure only if you are using datastore as `elasticsearch` in Skedler 4.x
    # The Elasticsearch instance to use for all your queries.
    # elasticsearchUrl: "http://localhost:9200"
    # skedlerIndex: ".skedler"
    # If Elasticsearch uses security or basic auth like xpack, searcguard, opendistro etc, mention below.
    # elasticsearchAuthType: "xpack"
    # If Elasticsearch uses security or basic auth, add the security username and password here for Skedler.
    # skedlerElasticsearchUsername: user
    # skedlerElasticsearchPassword: pass
